using Domain.Enums;

namespace Domain.Entities
{
    public class Payment
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();
        public string? LoanId { get; set; }
        public string? UserProfileId { get; set; }

        // Used to verify payment and prevent duplicates, generated by paystack.
        public string PaystackReference { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public PaymentStatus Status { get; set; } = PaymentStatus.Pending;
        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

        // Updated when webhook confirms payment
        public DateTime? UpdatedDate { get; set; }

        // Raw JSON response from Paystack, for debugging and audit purposes. Contains full transaction details from Paystack
        public string? PaystackResponse { get; set; }

        // User is redirected here, from Paystack, to complete payment
        public string? AuthorizationUrl { get; set; }
    }
}
